FROM mcr.microsoft.com/powershell:latest

LABEL maintainer="ericghoubiguian@live.fr"

COPY ./ /UniversalWeatherPowershell

WORKDIR /UniversalWeatherPowershell/samples/integratedSamples

#RUN ["pswh.exe"]

SHELL ["powershell"]
